"""
Nubra SDK — Self-Setup Automated Login
=======================================
Flow every time you run it:

    1. Check .env for a TOTP secret
         - present  -> TOTP already set up by this script -> go straight to auto-login
         - missing  -> run guided TOTP setup (Steps A-C below), save secret, then login
    2. Auto-login with TOTP (phone + MPIN from .env, TOTP code generated by pyotp)
    3. Reuse the session (option chain demo included)

Guided TOTP setup (runs only once, when the secret is missing):
    Step A. OTP login              -> you type the OTP from SMS (one time only)
    Step B. totp_generate_secret() -> secret auto-saved into .env
    Step C. totp_enable()          -> TOTP code auto-filled by pyotp, MPIN from .env
    After this, every future run is 100% hands-free.

Credentials come from the repo-root .env (and .env.local, which overrides it).
Both the NUBRA_-prefixed keys used across this repo and the SDK's own plain
names are accepted:
    NUBRA_PHONE / PHONE_NO
    NUBRA_MPIN  / MPIN
    NUBRA_TOTP_SECRET / TOTP_SECRET   # added automatically by this script

Install:
    pip install nubra-sdk pyotp python-dotenv

Note: the SDK has no documented "is TOTP enabled?" API — the only methods are
totp_generate_secret / totp_enable / totp_disable. So this script treats the
presence of a TOTP secret in .env as the "enabled" marker, and falls back to
re-setup if a TOTP login attempt fails.
"""

import builtins
import os
from pathlib import Path
import sys

import pyotp
from dotenv import load_dotenv, set_key

# Windows consoles default to cp1252, which can't encode the status glyphs the
# SDK (and this script) print — an otherwise-successful login would die with a
# UnicodeEncodeError on a stray emoji. Force UTF-8 on stdout/stderr so output is
# never the thing that fails. Python 3.7+ has reconfigure(); guard for safety.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

from nubra_python_sdk.start_sdk import InitNubraSdk, NubraEnv
from nubra_python_sdk.trading.trading_enum import TradingAPIVersion

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
# Load .env from the repo root (two levels up from go-backend/scripts/) so the
# script works no matter which directory it's launched from — not just when the
# CWD happens to contain a .env. Both files are optional; .env.local wins.
REPO_ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = REPO_ROOT / ".env"          # the file setup writes the secret back into
load_dotenv(ENV_FILE)
load_dotenv(REPO_ROOT / ".env.local", override=True)

ENV = NubraEnv.UAT          # UAT for V3 testing; switch to NubraEnv.PROD for live
USE_V3 = True               # requires SDK 0.4.5+ and Sentinel/OMS enabled on account

# V3 needs nubra-sdk 0.4.5+; older builds expose only V1/V2 on this enum and
# `TradingAPIVersion.V3` blows up with a bare AttributeError. Fail loudly here,
# and point at THIS interpreter — the usual cause is running the script with a
# different Python than the one where 0.4.5 is installed.
if USE_V3 and not hasattr(TradingAPIVersion, "V3"):
    sys.exit(
        "This nubra-sdk is too old for V3 (TradingAPIVersion has no V3).\n"
        f"Upgrade the SDK for the interpreter running this script:\n"
        f'    "{sys.executable}" -m pip install --upgrade "nubra-sdk==0.4.5"'
    )


def env_any(*names: str) -> str | None:
    """Return the first non-placeholder value among the given env names.

    The rest of this codebase (Go backend, sibling scripts, the root .env)
    uses NUBRA_-prefixed keys, while the Nubra SDK's own env_creds flow reads
    PHONE_NO / MPIN. Accept both so a single .env drives everything."""
    for name in names:
        value = (os.getenv(name) or "").strip()
        if value and not value.lower().startswith("your_"):
            return value
    return None


PHONE_NO = env_any("NUBRA_PHONE", "PHONE_NO")
MPIN = env_any("NUBRA_MPIN", "MPIN")

if not PHONE_NO or not MPIN:
    sys.exit(
        f"Add NUBRA_PHONE and NUBRA_MPIN to {ENV_FILE}, then rerun. "
        "(PHONE_NO / MPIN are also accepted.)"
    )

# The SDK's own env_creds=True login reads PHONE_NO / MPIN from the environment,
# so mirror the resolved values under those names for the SDK to pick up.
os.environ["PHONE_NO"] = PHONE_NO
os.environ["MPIN"] = MPIN


# ---------------------------------------------------------------------------
# AutoPrompt: answers the SDK's input() prompts automatically
# ---------------------------------------------------------------------------
class AutoPrompt:
    """Patches input() during SDK calls.
    - TOTP prompts  -> fresh pyotp code (if we have a secret)
    - phone prompts -> PHONE_NO from .env
    - MPIN prompts  -> MPIN from .env
    - OTP (SMS) prompts and anything unrecognized -> asks you normally.
    Note: checks 'totp' BEFORE 'otp', so SMS-OTP prompts still reach you."""

    def __init__(self, totp_secret=None):
        self.totp = pyotp.TOTP(totp_secret) if totp_secret else None

    def __enter__(self):
        self._real_input = builtins.input

        def patched(prompt=""):
            p = str(prompt).lower()
            if "totp" in p and self.totp:
                code = self.totp.now()
                print(f"{prompt}{code}  [auto]")
                return code
            if ("phone" in p or "mobile" in p) and "otp" not in p:
                print(f"{prompt}{PHONE_NO}  [auto]")
                return PHONE_NO
            if "mpin" in p:
                print(f"{prompt}****  [auto]")
                return MPIN
            return self._real_input(prompt)   # SMS OTP / unknown -> human

        builtins.input = patched
        return self

    def __exit__(self, *exc):
        builtins.input = self._real_input
        return False


# ---------------------------------------------------------------------------
# One-time TOTP setup (Steps A-C)
# ---------------------------------------------------------------------------
def setup_totp():
    print("\n" + "=" * 60)
    print("TOTP is not set up yet. Running one-time setup...")
    print("You'll need the OTP that arrives by SMS. After this,")
    print("all future logins are fully automatic.")
    print("=" * 60)

    # Step A: OTP login to get a setup session (phone/MPIN auto, OTP manual)
    print("\n[Step A] Logging in with SMS OTP...")
    with AutoPrompt():
        setup_client = InitNubraSdk(ENV)

    # Step B: generate secret and persist it to the repo-root .env under the
    # NUBRA_TOTP_SECRET key so the next run (and the Go backend) picks it up.
    print("\n[Step B] Generating TOTP secret...")
    secret = setup_client.totp_generate_secret()
    set_key(str(ENV_FILE), "NUBRA_TOTP_SECRET", secret)
    os.environ["NUBRA_TOTP_SECRET"] = secret
    print(f"    Secret saved to {ENV_FILE} as NUBRA_TOTP_SECRET")
    print("    (Optional: also add it to Google Authenticator as a backup.)")

    # Step C: enable TOTP — code auto-generated, MPIN auto-filled
    print("\n[Step C] Enabling TOTP on the account...")
    with AutoPrompt(totp_secret=secret):
        setup_client.totp_enable()

    print("\n✅ TOTP setup complete. Future runs are hands-free.\n")
    return secret


# ---------------------------------------------------------------------------
# Auto-login (uses saved secret; runs setup first if secret is missing)
# ---------------------------------------------------------------------------
def login():
    secret = env_any("NUBRA_TOTP_SECRET", "TOTP_SECRET")

    if not secret:                       # "enabled?" check -> not set up yet
        secret = setup_totp()

    kwargs = dict(totp_login=True, env_creds=True)
    if USE_V3:
        kwargs["trading_version"] = TradingAPIVersion.V3

    try:
        with AutoPrompt(totp_secret=secret):
            nubra = InitNubraSdk(ENV, **kwargs)
    except Exception as e:
        print(f"\nTOTP login failed ({e}).")
        ans = input("TOTP may have been disabled/reset. Redo setup now? [y/N] ")
        if ans.strip().lower() != "y":
            raise
        secret = setup_totp()
        with AutoPrompt(totp_secret=secret):
            nubra = InitNubraSdk(ENV, **kwargs)

    print(f"\n✅ Logged in to Nubra ({ENV}) — session ready for reuse.")
    return nubra


# ---------------------------------------------------------------------------
# Demo: reuse the session for option chain work
# ---------------------------------------------------------------------------
def demo_option_chain(nubra, underlying="NIFTY"):
    """Prints ATM CE/PE snapshot. Signature per docs:
    option_chain(instrument, expiry="YYYYMMDD" optional, exchange="NSE"/"BSE"/"MCX")."""
    from nubra_python_sdk.marketdata.market_data import MarketData

    md = MarketData(nubra)
    result = md.option_chain(underlying, exchange="NSE")

    chain = result.chain
    print(f"\nOption chain for {underlying}")
    print(f"Current Price : {chain.current_price}")
    print(f"ATM Strike    : {chain.at_the_money_strike}")
    print(f"Expiries      : {chain.all_expiries}")

    atm_ce = next((o for o in chain.ce
                   if o.strike_price == chain.at_the_money_strike), None)
    atm_pe = next((o for o in chain.pe
                   if o.strike_price == chain.at_the_money_strike), None)
    if atm_ce:
        print(f"ATM CE  ltp={atm_ce.last_traded_price}  "
              f"oi={atm_ce.open_interest}  iv={atm_ce.iv}")
    if atm_pe:
        print(f"ATM PE  ltp={atm_pe.last_traded_price}  "
              f"oi={atm_pe.open_interest}  iv={atm_pe.iv}")


if __name__ == "__main__":
    client = login()
    demo_option_chain(client)
    # Keep using `client` across instruments / market data / trading modules.
    # Only call client.logout() when you deliberately want to end the session.
