#!/usr/bin/env python3
"""Upstox OAuth auto-login (fully automated, headless).

Ported from a proven Playwright implementation. Upstox's login is a fixed
3-step page with STABLE element ids, and because the second factor is a TOTP we
generate ourselves from the user's secret, the whole flow is hands-free — no
manual OTP, no password/DOB (Upstox login does not use those):

  1. #mobileNum  ← phone           → click #getOtp
  2. #otpNum     ← generated TOTP  → click #continueBtn
  3. #pinCode    ← PIN             → click #pinContinueBtn
  4. intercept the redirect to redirect_uri?code=... and print the code

I/O contract with the Go backend:
  * Input: one JSON object on argv[1] OR stdin:
      {"authUrl","redirectUri","phone","pin","totp","headless"}
    (`totp` is the already-generated 6-digit code — Go generates it so the TOTP
     algorithm stays in one place, matching Angel's.)
  * Output (last stdout line): {"success":true,"code":"..."} or
      {"success":false,"error":"..."}
"""

import json
import sys
import time


def emit(obj):
    sys.stdout.write(json.dumps(obj) + "\n")
    sys.stdout.flush()


def log(msg):
    sys.stderr.write(str(msg) + "\n")
    sys.stderr.flush()


def read_input():
    raw = sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()
    try:
        return json.loads(raw)
    except Exception as e:
        emit({"success": False, "error": f"invalid input json: {e}"})
        sys.exit(1)


def main():
    cfg = read_input()
    auth_url = cfg.get("authUrl")
    redirect_uri = cfg.get("redirectUri", "")
    phone = cfg.get("phone", "")
    pin = cfg.get("pin", "")
    totp = cfg.get("totp", "")
    headless = bool(cfg.get("headless", True))

    if not auth_url or not phone or not pin or not totp:
        emit({"success": False, "error": "authUrl, phone, pin and totp are required"})
        return

    try:
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support.ui import WebDriverWait
        from selenium.webdriver.support import expected_conditions as EC
    except ImportError:
        emit({"success": False,
              "error": "selenium not installed — run: pip install -r go-backend/scripts/requirements.txt"})
        return

    options = Options()
    if headless:
        options.add_argument("--headless=new")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--window-size=460,780")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])

    driver = None
    try:
        driver = webdriver.Chrome(options=options)  # Selenium 4.6+ auto-manages the driver
        wait = WebDriverWait(driver, 25)
        driver.get(auth_url)

        # ── Step 1: Mobile number → Get OTP ──────────────────────────────────
        _type(driver, wait, [(By.ID, "mobileNum"),
                             (By.CSS_SELECTOR, "input[type='tel']"),
                             (By.NAME, "mobileNum")], phone, "mobile")
        _click(driver, wait, [(By.ID, "getOtp"),
                              (By.XPATH, "//button[contains(.,'Get OTP') or contains(.,'Continue') or contains(.,'Next')]")], "getOtp")
        log("[upstox-login] submitted mobile, waiting for OTP screen…")

        # ── Step 2: TOTP (generated by Go, passed in) → Continue ─────────────
        _type(driver, wait, [(By.ID, "otpNum"),
                             (By.CSS_SELECTOR, "input[autocomplete='one-time-code']"),
                             (By.CSS_SELECTOR, "input[type='tel']")], totp, "totp")
        _click(driver, wait, [(By.ID, "continueBtn"),
                              (By.XPATH, "//button[contains(.,'Continue') or contains(.,'Verify') or contains(.,'Next')]")], "continueBtn")
        log("[upstox-login] submitted TOTP, waiting for PIN screen…")

        # ── Step 3: PIN → Continue ───────────────────────────────────────────
        # Upstox's PIN field id has varied (#pinCode / #pin / a bare input); try
        # several, and drive it via JS+events so React registers the value.
        _type(driver, wait, [(By.ID, "pinCode"),
                             (By.ID, "pin"),
                             (By.CSS_SELECTOR, "input[type='password']"),
                             (By.CSS_SELECTOR, "input[inputmode='numeric']"),
                             (By.CSS_SELECTOR, "input[type='tel']")], pin, "pin")
        _click(driver, wait, [(By.ID, "pinContinueBtn"),
                              (By.XPATH, "//button[contains(.,'Continue') or contains(.,'Login') or contains(.,'Submit')]")], "pinContinueBtn")
        log("[upstox-login] submitted PIN, waiting for redirect…")

        # ── Step 4: Wait for redirect to redirect_uri?code=... ───────────────
        code = _await_code(driver, redirect_uri)
        if code:
            log("[upstox-login] got auth code")
            emit({"success": True, "code": code})
        else:
            _dump(driver, "no-redirect")
            emit({"success": False, "error": "timed out waiting for Upstox redirect code"})
    except Exception as e:
        _dump(driver, "exception")
        emit({"success": False, "error": f"{type(e).__name__}: {e}"})
    finally:
        if driver:
            try:
                driver.quit()
            except Exception:
                pass


def _type(driver, wait, locators, value, label):
    """Wait for the first matching visible input, then set it via JS + native
    input/change events so React-controlled fields (Upstox) accept the value."""
    from selenium.webdriver.support import expected_conditions as EC
    el = _first_present(driver, wait, locators, label)
    try:
        el.clear()
    except Exception:
        pass
    el.click()
    el.send_keys(value)
    # Belt-and-braces: also set the value via JS and fire events, because some
    # Upstox inputs ignore send_keys until a React onChange is triggered.
    driver.execute_script(
        "arguments[0].value = arguments[1];"
        "arguments[0].dispatchEvent(new Event('input', {bubbles:true}));"
        "arguments[0].dispatchEvent(new Event('change', {bubbles:true}));",
        el, value)
    log(f"[upstox-login] filled {label}")


def _click(driver, wait, locators, label):
    el = _first_present(driver, wait, locators, label)
    # Prefer a normal click; fall back to a JS click if the button is overlaid.
    try:
        el.click()
    except Exception:
        driver.execute_script("arguments[0].click();", el)
    log(f"[upstox-login] clicked {label}")


def _first_present(driver, wait, locators, label, timeout=25):
    """Return the first locator that becomes present within the timeout."""
    end = time.time() + timeout
    last_err = None
    while time.time() < end:
        for by, sel in locators:
            try:
                el = driver.find_element(by, sel)
                if el.is_displayed():
                    return el
            except Exception as e:
                last_err = e
        time.sleep(0.3)
    raise RuntimeError(f"could not find {label} (tried {len(locators)} selectors): {last_err}")


def _dump(driver, tag):
    """Save the current page HTML + a screenshot next to the script so we can see
    exactly what Upstox rendered when a step failed."""
    if not driver:
        return
    try:
        import os
        here = os.path.dirname(os.path.abspath(__file__))
        with open(os.path.join(here, f"upstox_fail_{tag}.html"), "w", encoding="utf-8") as f:
            f.write(driver.page_source or "")
        driver.save_screenshot(os.path.join(here, f"upstox_fail_{tag}.png"))
        log(f"[upstox-login] saved diagnostics upstox_fail_{tag}.html/.png (url={driver.current_url})")
    except Exception as e:
        log(f"[upstox-login] dump failed: {e}")


def _await_code(driver, redirect_uri, timeout=30):
    """Poll the browser URL until Upstox redirects with ?code= (or ?error=).

    The moment the redirect URL appears we call window.stop() so the browser
    does NOT finish loading our backend's /upstox/callback page — that page would
    otherwise exchange (and burn) the single-use code before Go can. Go performs
    the one and only token exchange with the code we return here.
    """
    from urllib.parse import urlparse, parse_qs
    base = redirect_uri.split("?")[0] if redirect_uri else ""
    end = time.time() + timeout
    while time.time() < end:
        url = driver.current_url or ""
        if (base and url.startswith(base)) or "code=" in url or "error=" in url:
            try:
                driver.execute_script("window.stop();")
            except Exception:
                pass
            qs = parse_qs(urlparse(url).query)
            if qs.get("code"):
                return qs["code"][0]
            if qs.get("error"):
                raise RuntimeError(qs.get("error_description", qs["error"])[0])
        time.sleep(0.25)
    return None


if __name__ == "__main__":
    main()
